spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin

  thymeleaf:
    cache: true
    check-template-location: true
    check-template: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/

  redis:
    host: localhost
    port: 6379
    timeout: 5000ms

