spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin

  thymeleaf:
    cache: true
    check-template-location: true
    check-template: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
